"""Pine Script v6 code templates for strategy export.

These templates are used by PineExporter to assemble valid Pine Script files.
"""

# Main strategy header
PINE_HEADER = """//@version=6
strategy("{name}", overlay={overlay}, margin_long=100, margin_short=100,
         default_qty_type=strategy.percent_of_equity, default_qty_value={qty_pct},
         commission_type=strategy.commission.percent, commission_value={commission},
         slippage={slippage})

// Generated by Trading Backtest Engine
// Strategy: {name} {version}
// {description}
"""

# Input templates
PINE_INPUT_INT = 'input.int({default}, "{title}", minval={min}, maxval={max})'
PINE_INPUT_FLOAT = 'input.float({default}, "{title}", minval={min}, maxval={max}, step={step})'
PINE_INPUT_BOOL = 'input.bool({default}, "{title}")'
PINE_INPUT_STRING = 'input.string("{default}", "{title}")'

# Indicator templates
PINE_INDICATORS = {
    "sma": {
        "code": "{var} = ta.sma(close, {length})",
        "plot": 'plot({var}, "{title}", color=color.blue)',
    },
    "ema": {
        "code": "{var} = ta.ema(close, {length})",
        "plot": 'plot({var}, "{title}", color=color.orange)',
    },
    "wma": {
        "code": "{var} = ta.wma(close, {length})",
        "plot": 'plot({var}, "{title}", color=color.purple)',
    },
    "rsi": {
        "code": "{var} = ta.rsi(close, {length})",
        "plot": None,  # Typically plotted in separate pane
    },
    "macd": {
        "code": "[{var}_macd, {var}_signal, {var}_hist] = ta.macd(close, {fast}, {slow}, {signal})",
        "plot": None,
    },
    "bbands": {
        "code": "[{var}_mid, {var}_upper, {var}_lower] = ta.bb(close, {length}, {std})",
        "plot": 'plot({var}_upper, "BB Upper", color=color.gray)\nplot({var}_mid, "BB Mid", color=color.gray)\nplot({var}_lower, "BB Lower", color=color.gray)',
    },
    "atr": {
        "code": "{var} = ta.atr({length})",
        "plot": None,
    },
    "adx": {
        "code": "[{var}_plus, {var}_minus, {var}_adx] = ta.dmi({length}, {length})",
        "plot": None,
    },
    "stoch": {
        "code": "{var}_k = ta.stoch(close, high, low, {k})\n{var}_d = ta.sma({var}_k, {d})",
        "plot": None,
    },
    "cci": {
        "code": "{var} = ta.cci(high, low, close, {length})",
        "plot": None,
    },
    "mfi": {
        "code": "{var} = ta.mfi(hlc3, {length})",
        "plot": None,
    },
    "obv": {
        "code": "{var} = ta.obv",
        "plot": None,
    },
    "vwap": {
        "code": "{var} = ta.vwap(hlc3)",
        "plot": 'plot({var}, "VWAP", color=color.purple)',
    },
    "supertrend": {
        "code": "[{var}_value, {var}_dir] = ta.supertrend({multiplier}, {length})",
        "plot": None,
    },
    "psar": {
        "code": "{var} = ta.sar({af}, {max_af}, {af})",
        "plot": 'plot({var}, "PSAR", style=plot.style_cross, color=color.gray)',
    },
    "willr": {
        "code": "{var} = ta.wpr({length})",
        "plot": None,
    },
    "roc": {
        "code": "{var} = ta.roc(close, {length})",
        "plot": None,
    },
    "donchian": {
        "code": "[{var}_upper, {var}_lower] = ta.donchian({length})",
        "plot": 'plot({var}_upper, "DC Upper", color=color.teal)\nplot({var}_lower, "DC Lower", color=color.teal)',
    },
}

# Entry/exit templates
PINE_ENTRY_LONG = 'strategy.entry("{id}", strategy.long)'
PINE_ENTRY_SHORT = 'strategy.entry("{id}", strategy.short)'
PINE_EXIT = 'strategy.exit("{id}", from_entry="{from_entry}", stop={stop}, limit={limit})'
PINE_CLOSE = 'strategy.close("{id}")'

# Condition templates
PINE_CROSSOVER = "ta.crossover({a}, {b})"
PINE_CROSSUNDER = "ta.crossunder({a}, {b})"

# Full strategy template (used when structured metadata is available)
PINE_FULL_TEMPLATE = """//@version=6
strategy("{name}", overlay={overlay}, margin_long=100, margin_short=100,
         default_qty_type=strategy.percent_of_equity, default_qty_value={qty_pct},
         commission_type=strategy.commission.percent, commission_value={commission},
         slippage={slippage})

// ── Inputs ──────────────────────────────────────────
{inputs}

// ── Indicators ──────────────────────────────────────
{indicators}

// ── Conditions ──────────────────────────────────────
{conditions}

// ── Entries & Exits ─────────────────────────────────
{entries}

// ── Plots ───────────────────────────────────────────
{plots}
"""
